internal enum class TokenType {
    END_OF_INPUT,
    KEYWORD_BEGIN, KEYWORD_END, KEYWORD_INT, KEYWORD_BIN,
    OP_OR, OP_AND, OP_XOR, OP_SUB, OP_ADD, OP_MUL, OP_DIV,
    OP_NEGATE, OP_ASSIGN,
    IDENTIFIER, INTEGER, B_ZERO, B_ONE,
    L_BRACKET, R_BRACKET, COMMA, SEMICOLON
}